# -*- coding: utf-8 -*-
"""DataGen (2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QeQvMQo1DDKW-JR2zlPPk02_672ZJl04
"""

import os, warnings
import numpy as np
import pandas as pd
from scipy import stats
import matplotlib.pyplot as plt
import matplotlib.ticker as mtick
import matplotlib.patches as mpatches
from matplotlib.gridspec import GridSpec
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

"""Macros from CitiBank Report"""

np.random.seed(21052001)
N_ACCOUNTS = 10000
START_DATE = pd.Timestamp("2021-01-01")
END_DATE   = pd.Timestamp("2025-12-31")

"""Functions here:"""

def q(date):
    return (date.year, (date.month - 1) // 3 + 1)

"""1. Account Static Attributes"""

print("Generating account-level static attributes...")

card_type = np.random.choice(["GPCC","PLCC","Installment"], N_ACCOUNTS,
                              p=[0.62, 0.31, 0.07])

# Origination quarter — uniform spread 2021Q1 to 2024Q4 (so all have some history)
quarters = pd.date_range("2015-01-01", "2020-12-01", freq="QS")
orig_date = np.random.choice(quarters, N_ACCOUNTS)
orig_date = pd.to_datetime(orig_date)

# Demographics
age = np.clip(np.random.normal(42, 12, N_ACCOUNTS).astype(int), 21, 80) # on 2025-12-31

# Generate raw incomes
raw_incomes = np.random.lognormal(np.log(69), 0.70, N_ACCOUNTS)

income_k = np.where(raw_incomes < 18, np.random.uniform(10, 19.9, N_ACCOUNTS), raw_incomes)
income_k = np.where(income_k > 450, np.random.uniform(450, 600, N_ACCOUNTS), income_k)
income_k = np.round(income_k, 2)

# income_k = np.clip(np.random.lognormal(np.log(69), 0.75, N_ACCOUNTS), 12.5, 450).round(1)
gender     = np.random.choice(["M","F","Non-Binary"], N_ACCOUNTS, p=[0.48,0.49,0.03])
state_list = ["CA","TX","FL","NY","IL","PA","OH","GA","NC","MI", "NJ","VA","WA","AZ","MA","TN","IN","MO","MD","WI"]
state = np.random.choice(state_list, N_ACCOUNTS, p=np.ones(20)/20)
employment = np.random.choice(["Employed","Self-Employed","Retired","Student","Unemployed"], N_ACCOUNTS, p=[0.62,0.16,0.11,0.06,0.05])

student_mask = employment == "Student"
age[student_mask] = np.clip(age[student_mask], 21, 27)

retired_mask = employment == "Retired"
age[retired_mask] = np.clip(age[retired_mask], 55, 80)


housing = np.random.choice(["Own","Rent","Other"], N_ACCOUNTS, p=[0.54,0.40,0.06])
education = np.random.choice(["High School","Some College","Bachelor","Graduate"], N_ACCOUNTS, p=[0.28,0.25,0.30,0.17])
marital    = np.random.choice(["Single","Married","Divorced","Widowed"], N_ACCOUNTS, p=[0.38, 0.46, 0.12, 0.04])

adult_marital_mask = np.isin(marital, ["Married", "Divorced", "Widowed"])
age[adult_marital_mask] = np.clip( age[adult_marital_mask], 25, 80)

num_dependents = np.random.choice([0,1,2,3,4], N_ACCOUNTS, p=[0.35,0.25,0.25,0.10,0.05])

"""2. Bureau / Credit Score Attributes"""

# ──  ───────────────────────────────────────
# FICO correlated with income & age

fico_base = np.clip(580 + (income_k / 2) + (age - 21) / 70 * 50 + 10, 300, 850)
fico_noise = np.random.normal(0, 50, N_ACCOUNTS)
fico_score = np.clip((fico_base + fico_noise).astype(int), 300, 850)

# VantageScore ~ FICO + small divergence
vantage_score = np.clip(fico_score + np.random.randint(-20, 20, N_ACCOUNTS), 300, 850)

# Bureau tradeline attributes
num_tradelines      = np.clip(np.random.poisson(7, N_ACCOUNTS), 1, 35)
num_derog_marks     = np.where(fico_score < 620, np.random.poisson(2.5, N_ACCOUNTS), np.random.poisson(0.3, N_ACCOUNTS))
num_derog_marks     = np.clip(num_derog_marks, 0, 10)
oldest_account_yrs  = np.clip(np.random.exponential(8, N_ACCOUNTS), 0.5, age).round(1)
bureau_inquiries_6m = np.clip(np.random.poisson(1.5, N_ACCOUNTS), 0, 12)
total_debt_k        = np.clip(np.random.lognormal(np.log(25), 0.9, N_ACCOUNTS), 0, 500).round(1)
debt_to_income      = np.clip(total_debt_k / income_k, 0, 10).round(3)
bankruptcy_flag     = (fico_score < 580) & (np.random.rand(N_ACCOUNTS) < 0.08)

"""3. Card Product Attributes"""

# Existing FICO distribution
fico_base = np.clip(600 + (income_k*1.5) + (age - 21)*0.5 , 300, 850)
fico_noise = np.random.normal(0, 40, N_ACCOUNTS)
fico_score = np.clip((fico_base + fico_noise),300,850)

low_mask = (fico_score >= 450) & (fico_score <= 620)
fico_score[low_mask] = np.clip(np.random.normal(550,70,size=low_mask.sum()), 350, 650)
high_mask = (fico_score >650) & (fico_score <= 850)
fico_score[high_mask] = np.clip(np.random.normal( loc=680, scale=30, size=high_mask.sum()), 600, 850)

# Final integer conversion
fico_score = np.clip(fico_score*np.random.normal(1, 0.005), 350 , 843)
fico_score = fico_score.astype(int)

income_norm = (income_k - 10) / (120- 10)
fico_norm = ((fico_score - 300)/ 550)
combined_score = (income_norm + fico_norm)/1.5

base_limit_units = np.where(card_type == "GPCC", 80 * combined_score, np.where( card_type == "PLCC", 45 * combined_score, 60 * combined_score))

credit_limit = np.clip(np.round(base_limit_units * np.random.lognormal(0, 0.15, N_ACCOUNTS)) * 50, 500, income_k*1000/12*0.8)

apr = np.where(fico_score < 580, np.random.uniform(20, 24, N_ACCOUNTS), np.where(fico_score < 660, np.random.uniform(17, 20, N_ACCOUNTS), np.where(
            fico_score < 720, np.random.uniform(15, 18.5, N_ACCOUNTS), np.where( fico_score > 750, np.random.uniform(12, 15, N_ACCOUNTS), np.random.uniform(16, 18.9, N_ACCOUNTS)
            )
        )
    )
).round(2)

channel = np.random.choice(["Direct Mail","Online","In-Store","Branch","Pre-Approved"], N_ACCOUNTS, p=[0.25,0.35,0.20,0.10,0.10])

# Partner (for PLCC)
plcc_partners = ["Amazon","Target","Walmart","Home Depot","Costco","Best Buy","Macy's","Gap"]
partner = np.where(card_type=="PLCC",np.random.choice(plcc_partners, N_ACCOUNTS), "N/A")

""" 4. Behavioral / Monthly Snapshot (latest month = Dec-2025)"""

# Utilization inversely correlated with FICO
util_mean = np.clip(0.550- (fico_score - 450) / 850 * 0.660, 0.075, 0.925)
k = 30
alpha = util_mean * k
beta = (1 - util_mean) * k
utilization = np.clip(np.random.beta(alpha, beta, N_ACCOUNTS), 0.10, 1.0).round(4)

# Monthly spend (higher FICO → higher spend)
monthly_spend_base = income_k * 1000* 0.06 + (fico_score - 580) * 2
monthly_spend_behavioural = np.clip(np.random.lognormal(np.log(monthly_spend_base + 50), 0.25), 150, 37000).round(2)

current_balance = np.round(utilization * credit_limit, 2)

# Payment behavior
# min_payment_ratio = np.random.choice([1.0, 0.5, 0.015, 0.0], N_ACCOUNTS, p=[0.15, 0.35, 0.43, 0.07])  # full/half/min/skip
min_payment_ratio = np.random.beta(3, 6, N_ACCOUNTS)
months_on_book_initial = ((pd.Timestamp("2021-01-01") - orig_date).days / 30.44).astype(int)

# Revolving vs transactor
prob_pay_full = np.random.beta(7.5, 8, N_ACCOUNTS)

base_spend_frac = np.clip( np.random.lognormal(-0.9, 0.8, N_ACCOUNTS), 0.01, 0.99)

"""5. Delinquency Status (t-1 snapshot)

"""



base_dpd = np.random.choice(
    [0,1,2,3,4,5,6],
    size=N_ACCOUNTS,
    p=[0.99,0.004,0.003,0.001,0.001,0.001,0.00])

risk_shift = np.where(fico_score < 580,np.random.choice([0,1,2,3], size=N_ACCOUNTS, p=[0.92,0.04,0.03, 0.01]),
    np.where(fico_score < 660, np.random.choice([0,1,2], size=N_ACCOUNTS, p=[0.95,0.03,0.02]),
    np.where(fico_score < 750, np.random.choice([0,1,2,3], size = N_ACCOUNTS, p=[0.97,0.01,0.01,0.01]),
    np.where(fico_score >= 750, np.random.choice([0,1,2,3], size = N_ACCOUNTS, p=[0.99,0.005,0.003,0.002]),
    0)
            )))

dpd_bucket = np.clip(base_dpd + risk_shift, 0, 5)

opening_balanceOnD1 = np.clip(np.round(credit_limit* utilization* np.random.normal(3, 1, N_ACCOUNTS), 2), 0, credit_limit )

interest = np.round(opening_balanceOnD1 * (apr / 100) / 12, 2)

monthly_spend = np.clip(np.minimum( monthly_spend_behavioural, credit_limit*1.1 - opening_balanceOnD1 - interest)*np.random.normal(0.0, 0.2), 100, credit_limit)
statement_balance = (opening_balanceOnD1  + monthly_spend)

payment = statement_balance*np.random.normal(0.9, 0.05)*prob_pay_full
payment = np.minimum( payment, statement_balance)
payment = np.round(payment, 2)

closing_balanceOnM1 = np.clip(np.round(statement_balance - payment,2), 0, credit_limit)

available_limit = np.round( credit_limit - closing_balanceOnM1,  2)

"""7. Assemble DataFrame

"""

plt.hist(opening_balanceOnD1)
plt.show()
np.mean(opening_balanceOnD1)

# ── ──────────────────────────────────────────────────────
print("Assembling account-level dataset...")

df = pd.DataFrame({

    # Identifiers
    "account_id":          [f"USCC{str(i).zfill(6)}" for i in range(1, N_ACCOUNTS+1)],
    "orig_date":           orig_date,
    "vintage_year":        orig_date.year,
    "vintage_quarter":     orig_date.to_period("Q").astype(str),
    "openingBalanceOnD1":  opening_balanceOnD1,
    "closingBalance": closing_balanceOnM1,
    "paymentMade": payment,
    "interestToBePaidFromPrevMonth":interest,
    "limitAvailable": available_limit,

    # Demographics
    "age":                 age,
    "gender":              gender,
    "income_k":            income_k,
    "state":               state,
    "employment_status":   employment,
    "housing_status":      housing,
    "education_level":     education,
    "marital_status":      marital,
    "num_dependents":      num_dependents,

    # Credit Bureau
    "fico_score":          fico_score,
    "vantage_score":       vantage_score,
    "num_tradelines":      num_tradelines,
    "num_derog_marks":     num_derog_marks,
    "oldest_account_yrs":  oldest_account_yrs,
    "bureau_inquiries_6m": bureau_inquiries_6m,
    "total_debt_k":        total_debt_k,
    "debt_to_income":      debt_to_income,
    "bankruptcy_flag":     bankruptcy_flag.astype(int),

    # Product
    "card_type":           card_type,
    "partner":             partner,
    "credit_limit":        credit_limit,
    "apr":                 apr,
    "channel":             channel,
    "mob_i": months_on_book_initial,

    # Behavioral
    "utilization_rate_behavioural":    utilization,
    "monthly_spend_behavioural":       monthly_spend_behavioural,
    "min_payment_ratio_behavioural":   min_payment_ratio,
    "prob_pay_full":       prob_pay_full,
    "base_spend_frac":     base_spend_frac.round(4),
    # Delinquency
    "dpd_bucket":          dpd_bucket,
    "dpd_label": pd.Categorical(np.where(dpd_bucket == 0, "Current", np.where(dpd_bucket == 1, "30 DPD", np.where(dpd_bucket == 2, "60 DPD", np.where(dpd_bucket == 3, "90 DPD", np.where(dpd_bucket == 4, "120 DPD", np.where(dpd_bucket == 5, "150 DPD", "180+ DPD")))))), categories=[ "Current", "30 DPD", "60 DPD", "90 DPD", "120 DPD", "150 DPD", "180+ DPD"], ordered=True),

    # Risk Metrics
    "fico_tier":      pd.cut(fico_score, [299,580,620,660,720,850],
                               labels=["Deep Subprime","Subprime","Near Prime","Prime","Super Prime"]),
    "DayO_Util": closing_balanceOnM1/credit_limit


})

print(f"\n {len(df):,} accounts generated")
print(df.dtypes.to_string())
print("\nSample:\n", df.head(4).T)

df.to_csv("uscc_account_portfolio.csv", index=False)
print("\n Saved: uscc_account_portfolio.csv")

"""Simulation Loop!"""

dpd_dist = (
    df['dpd_label']
    .value_counts(sort=False)
    .reset_index()
)

dpd_dist.columns = ['dpd_label', 'count']

print(dpd_dist)

import numpy as np
np.random.seed(1222)

ALL_MONTHS  = pd.date_range("2021-01-01", "2025-12-01", freq="MS")  # 60 months
DPD_LABELS  = ["Current","30 DPD","60 DPD","90 DPD","120 DPD","150 DPD","180+ DPD"]
DPD_DAYS    = [0, 30, 60, 90, 120, 150, 180]          # bucket → days past due
N_BUCKETS   = 7                                         # 0..6 (6 = charge-off trigger)

print("\nSimulating monthly time-series ")


# ─────────────────────────────────────────────────────────────────────────────
# MAIN SIMULATION LOOP
# ─────────────────────────────────────────────────────────────────────────────

records = []
CHUNK = 500

for i in range(N_ACCOUNTS):
    if i % CHUNK == 0:
        print(f"  [{i:>6,}/{N_ACCOUNTS:,}] accounts processed...", flush=True)
    row = df.iloc[i]
    acct_id    = row[ "account_id"]
    orig       = row[ "orig_date"]
    c_limit    = row[ "credit_limit"]
    fico_i     = row[ "fico_score"]
    income_i   = row[ "income_k"]
    pfull_i    = row[ "prob_pay_full"]
    bsf_i      = row[ "base_spend_frac"]
    apr_i      = row[ "apr"] / 100 / 12   # monthly interest rate
    util_i     = row[ "utilization_rate_behavioural"]
    monthlySpend_i = row[ "monthly_spend_behavioural"]
    openingBalance_i = row[ "closingBalance"]
    dpd_i = row[ "dpd_bucket"]
    workingInterest = (row["closingBalance"] - row["paymentMade"])*apr_i
    workingPayment = row["paymentMade"]
    workingLateFess = 0
    availableLimit = row["limitAvailable"]

    bucket1BreachCount = 0
    if dpd_i >= 2:
        bucket1BreachCount = 1
    else:
        bucket1BreachCount = 0

    if dpd_i ==6:
        is_co   = True
    else:
        is_co = False
        min_due_paid = 1

    for m in ALL_MONTHS:
        if m < orig:
            continue
        min_due_paid = 1
        mob = (m.year - orig.year) * 12 + (m.month - orig.month)  # months on book
        gcl_ind = 0
        # ── Balance dynamics ──────────────────────────────────────────────────
        if not is_co:
            MAX_UTIL_THRESHOLD = 0.9 * np.random.normal(1, 0.002)

# --- OCL (unchanged) ---
            ocl_approved = (mob >= 12) and (fico_i >= 780) and (dpd_i == 0)
            if dpd_i <= 0:
                spend_cap = c_limit * 1.20     if ocl_approved else c_limit
            elif dpd_i <= 2:
                spend_cap = c_limit
            else:
                spend_cap = 0.0

            avail_limit = max(spend_cap - openingBalance_i + workingPayment, 0)
            util_vs_climit = openingBalance_i / c_limit
            excess_util = max(util_vs_climit - 0.80, 0)
            # spend_dampener = np.exp(-3.5 * excess_util)
# --- MOB ramp: new accounts spend conservatively ---
            mob_ramp = min(5.0, mob)  # 0.6 at MOB=1, 1.0 at MOB=5+

# --- Season: Q4 higher, Q1 lower (peak December, trough February) ---
            season = 2.0 + np.sin((m.month - 3) * np.pi / 6)

# --- Base spend: income proxy is the primary cap ---
# util_i drives how much of monthlySpend they actually put on the card
            base_spend = monthlySpend_i * util_i * mob_ramp
# --- Raw spend: dampener only meaningful near limit ---
            raw_spend = min(base_spend, avail_limit) * season * np.random.normal(10, 15)

            spend = np.clip(raw_spend, 0, avail_limit*0.75 if avail_limit > 0 else 0)

            # New balance before fees and payment
            new_balance_a = openingBalance_i + spend + workingInterest +workingLateFess

            if openingBalance_i - workingPayment + spend < c_limit:
                interest = np.clip((openingBalance_i - workingPayment + spend) * apr_i, 0 , openingBalance_i - workingPayment + spend)
            else:
                interest = np.clip((openingBalance_i - workingPayment + spend) * (apr_i+0.005), 0 , openingBalance_i - workingPayment + spend)

            # ── Late fee: $30, applied to 5% of delinquent billing records ──
            ocl_fee = 0.0
            # if new_balance_a > c_limit:
            #     raw_ocl_fee = 30.0
            #     over_limit = new_balance_a - c_limit
            #     # Fee cannot exceed amount over limit; cap to over_limit - 1
            #     ocl_fee = round(min(over_limit, raw_ocl_fee), 2)

            # Add fees to balance
            new_balance = new_balance_a + ocl_fee
            closing_balance = max(new_balance - workingPayment , 0.0)

            if dpd_i == 0:
                minDue = np.clip((openingBalance_i + spend)* 0.02 + workingInterest + workingLateFess + ocl_fee, 0, closing_balance)
            elif dpd_i == 1 or dpd_i == 2:
                minDue = np.clip((openingBalance_i + spend)* 0.05 + workingInterest + workingLateFess + ocl_fee, 0, closing_balance)
            else:
                minDue = np.clip((openingBalance_i + spend)* 0.5 + workingInterest + workingLateFess + ocl_fee, 0, closing_balance)

            if dpd_i == 0:
                if np.random.rand() >= pfull_i:
                    payment = np.clip(closing_balance * np.random.normal(0.95,0.005), minDue*1.5, closing_balance) #transactor behaviour / partial payer
                else:
                    payment = np.clip((minDue)*np.random.normal(1.20, 0.12),0, closing_balance) # revolver / partial payer
            elif dpd_i == 1 :
                if np.random.rand() > pfull_i:
                    payment = np.clip((minDue)*np.random.normal(0.95, 0.20),0, closing_balance)   # roll on / cure
                else:
                    payment = 0
            elif dpd_i == 2 :
                if np.random.rand() > pfull_i:
                    payment = np.clip((minDue)*np.random.normal(0.95, 0.10),0, closing_balance)
                else:
                    payment = 0
            elif dpd_i == 3 :
                if np.random.rand() > pfull_i:
                    payment = np.clip((minDue)*np.random.normal(0.85, 0.12),0, closing_balance)
                else:
                    payment = 0
            elif dpd_i == 4 :
                if np.random.rand() > pfull_i:
                    payment = np.clip((minDue)*np.random.normal(0.80, 0.12),0, closing_balance)
                else:
                    payment = 0
            else:
                if np.random.rand() > pfull_i:
                    payment = np.clip(minDue* np.random.normal(0.75, 0.08),0, closing_balance) # roll over / cure
                else:
                    payment = 0




            if payment < minDue :
                min_due_paid = 0


            payment = round(payment, 2)
            utilization = round(closing_balance / c_limit, 3) if c_limit > 0 else 0.0

        else:
            # Post charge-off: zero balance, zero spend, zero payment
            closing_balance     = 0.0
            spend       = 0.0
            payment     = 0.0
            utilization = 0.0
            late_fee    = 0.0
            ocl_fee     = 0.0
            interest    = 0.0


        # ── DPD State Transition ──────────────────────────────────────────────
        if not is_co:
            if min_due_paid == 0:
                dpd_i  = min(dpd_i +1, 6)
                if dpd_i == 6:
                    is_co = True
                    gcl_ind = 1
                if dpd_i == 1:
                    bucket1BreachCount += 1
            else:
                dpd_i = 0
        late_fee = 0.0
        if 6> dpd_i > 0:
            if dpd_i == 1 & bucket1BreachCount <= 3:
                late_fee = 0
                dpd_i = 0
            else:
                late_fee = 30.0

        records.append({
            # Keys
            "account_id":       acct_id,
            "month":            m,
            "month_num":        m.month,
            "year":             m.year,
            "quarter":          (m.month - 1) // 3 + 1,
            "months_on_book":   mob,
            # DPD State
            "dpd_bucket_num":   dpd_i,
            "dpd_bucket_label": DPD_LABELS[dpd_i],
            "dpd_days":         DPD_DAYS[min(dpd_i, 6)],
            "is_charged_off":   int(is_co),
            # Financials
            "opening_balance":  round(openingBalance_i,2),
            "closing_balance":  round(closing_balance, 2),
            "interest_income": round(interest,2),
            "ANR": round((openingBalance_i + closing_balance)/2,2),
            "cost_of_funds": 0.004*(openingBalance_i + closing_balance)/2,
            "interchange_income": round(0.010*spend,2),
            "credit_limit":     round(c_limit, 2),
            "availableLimit": round(c_limit - closing_balance + payment, 2),
            "utilization_rate": round(utilization,1),
            "minimumAmountDue": round(minDue,2),
            "monthly_spend_this_month":    round(spend, 2),
            "payment_amount":   round(payment, 2),
            "payment_ratio":    round(payment / max(openingBalance_i + spend, 1), 2),
            "late_fee":         round(late_fee, 2),
            "ocl_fee":          round(ocl_fee, 2),
            "gcl_ind": gcl_ind,

        })
        openingBalance_i = closing_balance
        workingInterest = interest
        workingPayment = payment
        workingLateFess = late_fee

print(f"\n  ✅ Simulation complete — {len(records):,} monthly observations")

"""Generating Final Dataset"""

print("\nAssembling panel dataframe...")
panel = pd.DataFrame(records)
panel["gcl"] = panel["closing_balance"] *panel["gcl_ind"]
# Merge static attributes (every row gets full account context)
# Drop credit_limit from static since it's already in the panel from the simulation loop
static_merge = df.drop(columns=["prob_pay_full","base_spend_frac","credit_limit", "utilization_rate_behavioural","monthly_spend_behavioural"
                               ])
panel = panel.merge(static_merge, on="account_id", how="left")

# Sort
panel = panel.sort_values(["account_id","month"]).reset_index(drop=True)

print(f"  Panel shape: {panel.shape}")
print(f"  Columns: {list(panel.columns)}")
print(f"\n  DPD distribution (all months):")
print(panel["dpd_bucket_label"].value_counts(normalize=True).mul(100).round(2).to_string())
print(f"\n  Charge-off rate across all obs: {panel['is_charged_off'].mean()*100:.2f}%")

# ─────────────────────────────────────────────────────────────────────────────
# 4. SAVE
# ─────────────────────────────────────────────────────────────────────────────
# print("\nSaving files...")

# # Full panel (large file)
# panel.to_csv("uscc_monthly_timeseries.csv", index=False)
# print(f"  💾 uscc_monthly_timeseries.csv  ({panel.shape[0]:,} rows × {panel.shape[1]} cols)")

# # Static accounts only (for joining)
# df.to_csv(
#     "uscc_static_accounts.csv", index=False
# )
# print(f"  💾 uscc_static_accounts.csv     ({len(df):,} rows × {len(df.columns)-2} cols)")

# print("\n✅ PART 2 DONE")

panel['gcl']=panel['closing_balance']*panel['gcl_ind']
recovery=0.25
panel['ncl']=panel['gcl']*(1-recovery)
panel['cnr']=panel['interest_income']-panel['cost_of_funds']+panel['interchange_income']+panel['late_fee']+panel['ocl_fee']
panel['opex']=(0.035)*panel['ANR']/12
panel['pnl']=panel['cnr']-panel['ncl']-panel['opex']

monthly = (panel.groupby("month")  # month should be a period/date column
                    .agg(ncl=("ncl", "sum"), anr=("ANR", "sum"), opex=("opex", "sum"),
                      interest_income=("interest_income", "sum"), interchange_income=("interchange_income", "sum"), late_fee=("late_fee", "sum"), ocl_fee=("ocl_fee", "sum")
                    ).reset_index())
monthly["cost_of_funds"] = monthly["anr"]*0.004
monthly["cnr"] = monthly["interest_income"] + monthly["interchange_income"] + monthly["late_fee"] - monthly["cost_of_funds"]
monthly["pnl"] = monthly["cnr"] - monthly["ncl"] - monthly["opex"]

plt.hist(panel["paymentMade"])
plt.show()

# monthly

PALETTE       = ["#003f5c","#2f4b7c","#665191","#a05195","#d45087",
                 "#f95d6a","#ff7c43","#ffa600"]
RISK_COLORS   = {"Deep Subprime":"#d62728","Subprime":"#ff7f0e",
                 "Near Prime":"#bcbd22","Prime":"#2ca02c","Super Prime":"#1f77b4"}
CARD_COLORS   = {"GPCC":"#003f5c","PLCC":"#a05195","Installment":"#ffa600"}

plt.rcParams.update({
    "figure.facecolor":"#f8f9fa","axes.facecolor":"#ffffff",
    "axes.grid":True,"grid.color":"#e0e0e0","grid.linewidth":0.6,
    "font.family":"DejaVu Sans","font.size":10,
    "axes.spines.top":False,"axes.spines.right":False,
    "axes.titlesize":13,"axes.titleweight":"bold",
})

OUTPUT_DIR = "output_charts"
os.makedirs(OUTPUT_DIR, exist_ok=True)

RECOVERY_RATE = 0.15   # assumed 15% recovery on charged-off balances
OPEX_RATE_ANN = 0.045  # 4.5% of ANR annualised allocated operating expense

def plot_CNR_rates(panel: pd.DataFrame):
    """NCL Rate trends by calendar month, quarter, and year."""

    # ── Monthly NCL Rate ──────────────────────────────────────────────────
    monthly = (panel.groupby("month")  # month should be a period/date column
                    .agg(cnr=("cnr", "sum"), anr=("ANR", "sum"))
                    .reset_index())
    monthly["cnr_rate"] = monthly["cnr"] / monthly["anr"].replace(0, np.nan) * 100

    # ── Quarterly NCL Rate ────────────────────────────────────────────────

# If panel has separate year and quarter columns
    panel["year_quarter"] = panel["year"].astype(str) + " " + panel["quarter"].astype(str)
# gives "2021 Q1", "2021 Q2" etc

    quarterly = (panel.groupby("year_quarter")
                  .agg(cnr=("cnr", "sum"), anr=("ANR", "sum"))
                  .reset_index()
                  .sort_values("year_quarter"))  # sort important so x-axis is ordered
    quarterly["cnr_rate"] = quarterly["cnr"] / (quarterly["anr"] / 3).replace(0, np.nan) * 100




    # ── Annual NCL Rate ───────────────────────────────────────────────────
    annual = (panel.groupby("year")
                   .agg(cnr=("cnr", "sum"), anr=("ANR", "sum"))
                   .reset_index())
    annual["cnr_rate"] = annual["cnr"] / (annual["anr"] / 12).replace(0, np.nan) * 100

    # ── Plot ──────────────────────────────────────────────────────────────
    fig, axes = plt.subplots(3, 1, figsize=(16, 14))
    fig.suptitle("cnr Rate Trends", fontsize=15, fontweight="bold")

    # Monthly
    ax = axes[0]
    ax.plot(monthly["month"].astype(str), monthly["cnr_rate"], lw=2, marker="o", markersize=3, color="steelblue")
    ax.yaxis.set_major_formatter(mtick.PercentFormatter())
    ax.set_title("Monthly cnr Rate")
    ax.set_xlabel("Month")
    ax.set_ylabel("cnr Rate %")
    ax.tick_params(axis="x", rotation=45)

    # Quarterly
    ax = axes[1]
    ax.plot(quarterly["year_quarter"].astype(str), quarterly["cnr_rate"], lw=2, marker="o", markersize=3, color="darkorange")
    ax.yaxis.set_major_formatter(mtick.PercentFormatter())
    ax.set_title("Quarterly cnr Rate  [sum(cnr) / avg(ANR) × 100]")
    ax.set_xlabel("Quarter")
    ax.set_ylabel("cnr Rate %")
    ax.tick_params(axis="x", rotation=45)

    # Annual
    ax = axes[2]
    ax.bar(annual["year"].astype(str), annual["cnr_rate"], color="seagreen", width=0.5)
    ax.yaxis.set_major_formatter(mtick.PercentFormatter())
    ax.set_title("Annual cnr Rate  [sum(cnr) / avg(ANR) × 100]")
    ax.set_xlabel("Year")
    ax.set_ylabel("cnr Rate %")

    plt.tight_layout()
    path = f"{OUTPUT_DIR}/05_cnr_rates.png"
    plt.savefig(path, dpi=150, bbox_inches="tight")
    plt.close()
    print(f"  ✔ Saved {path}")
plot_CNR_rates(panel)

def plot_ncl_rates(panel: pd.DataFrame):
    """NCL Rate trends by calendar month, quarter, and year."""

    # ── Monthly NCL Rate ──────────────────────────────────────────────────
    monthly = (panel.groupby("month")  # month should be a period/date column
                    .agg(ncl=("ncl", "sum"), anr=("ANR", "sum"))
                    .reset_index())
    monthly["ncl_rate"] = monthly["ncl"] / monthly["anr"].replace(0, np.nan) * 100

    # ── Quarterly NCL Rate ────────────────────────────────────────────────

# If panel has separate year and quarter columns
    panel["year_quarter"] = panel["year"].astype(str) + " " + panel["quarter"].astype(str)
# gives "2021 Q1", "2021 Q2" etc

    quarterly = (panel.groupby("year_quarter")
                  .agg(ncl=("ncl", "sum"), anr=("ANR", "sum"))
                  .reset_index()
                  .sort_values("year_quarter"))  # sort important so x-axis is ordered
    quarterly["ncl_rate"] = quarterly["ncl"] / (quarterly["anr"] / 3).replace(0, np.nan) * 100




    # ── Annual NCL Rate ───────────────────────────────────────────────────
    annual = (panel.groupby("year")
                   .agg(ncl=("ncl", "sum"), anr=("ANR", "sum"))
                   .reset_index())
    annual["ncl_rate"] = annual["ncl"] / (annual["anr"] / 12).replace(0, np.nan) * 100

    # ── Plot ──────────────────────────────────────────────────────────────
    fig, axes = plt.subplots(3, 1, figsize=(16, 14))
    fig.suptitle("NCL Rate Trends", fontsize=15, fontweight="bold")

    # Monthly
    ax = axes[0]
    ax.plot(monthly["month"].astype(str), monthly["ncl_rate"], lw=2, marker="o", markersize=3, color="steelblue")
    ax.yaxis.set_major_formatter(mtick.PercentFormatter())
    ax.set_title("Monthly NCL Rate")
    ax.set_xlabel("Month")
    ax.set_ylabel("NCL Rate %")
    ax.tick_params(axis="x", rotation=45)

    # Quarterly
    ax = axes[1]
    ax.plot(quarterly["year_quarter"].astype(str), quarterly["ncl_rate"], lw=2, marker="o", markersize=3, color="darkorange")
    ax.yaxis.set_major_formatter(mtick.PercentFormatter())
    ax.set_title("Quarterly NCL Rate  [sum(NCL) / avg(ANR) × 100]")
    ax.set_xlabel("Quarter")
    ax.set_ylabel("NCL Rate %")
    ax.tick_params(axis="x", rotation=45)

    # Annual
    ax = axes[2]
    ax.bar(annual["year"].astype(str), annual["ncl_rate"], color="seagreen", width=0.5)
    ax.yaxis.set_major_formatter(mtick.PercentFormatter())
    ax.set_title("Annual NCL Rate  [sum(NCL) / avg(ANR) × 100]")
    ax.set_xlabel("Year")
    ax.set_ylabel("NCL Rate %")

    plt.tight_layout()
    path = f"{OUTPUT_DIR}/04_ncl_rates.png"
    plt.savefig(path, dpi=150, bbox_inches="tight")
    plt.close()
    print(f"  ✔ Saved {path}")
plot_ncl_rates(panel)

def plot_pnl_waterfall(panel: pd.DataFrame):
    """Fig 06 — Full-portfolio annual P&L waterfall + quarterly trend + YoY P&L."""
    fig, axes = plt.subplots(1, 3, figsize=(24, 8))
    fig.suptitle("Portfolio P&L Analysis", fontsize=15, fontweight="bold")

    # ── Annual waterfall (all years combined) ─────────────────────────────────
    ax = axes[0]
    totals = {
        "Avg Net\nReceivables":  monthly["anr"].sum()/60,
        "Interest\nIncome":      monthly["interest_income"].sum()/5,
        "Interchange\nIncome":   monthly["interchange_income"].sum()/5,
        "Fee\nIncome":           (monthly["late_fee"].sum() + panel["ocl_fee"].sum())/5,
        "Total\nRevenue":        monthly["cnr"].sum()/5,
        "Net Credit\nLoss":      -monthly["ncl"].sum()/5,
        "Cost of\nFunds":        -monthly["cost_of_funds"].sum()/5,
        "OpEx":                  -monthly["opex"].sum()/5,
        "Net P&L":               monthly["pnl"].sum()/5,
    }
    labels  = list(totals.keys())
    values  = [v/1e6 for v in totals.values()]
    running = 0.0
    bottoms = []
    bar_colors = []
    for lab, val in zip(labels, values):
        if lab in ("Avg Net\nReceivables","Total\nRevenue","Net P&L"):
            bottoms.append(0); bar_colors.append("#2f4b7c")
            running = val
        elif val >= 0:
            bottoms.append(running); running += val; bar_colors.append("#2ca02c")
        else:
            running += val; bottoms.append(running); bar_colors.append("#d62728")
    bars = ax.bar(labels, values, bottom=bottoms, color=bar_colors, alpha=0.85,
                  edgecolor="white", width=0.6)
    for bar, v, b in zip(bars, values, bottoms):
        ypos = b + v + (abs(v)*0.02)
        ax.text(bar.get_x()+bar.get_width()/2, ypos,
                f"${v:,.0f}M", ha="center", va="bottom" if v>=0 else "top", fontsize=8)
    ax.set_title("Full Portfolio P&L Waterfall (5-Year Avg, $M)")
    ax.set_ylabel("$M"); ax.yaxis.set_major_formatter(mtick.FuncFormatter(lambda x,_:f"${x:,.0f}M"))
    ax.tick_params(axis="x", labelsize=8)

    # ── Quarterly P&L trend ────────────────────────────────────────────────────
    ax = axes[1]
    q_pnl = panel.groupby("yyyyq").agg(
        revenue=("cnr","sum"), ncl=("ncl","sum"),
        cof=("cost_of_funds","sum"), opex=("opex","sum"),
        anr=("ANR","sum")).reset_index()
    q_pnl["net_pnl"] = q_pnl["revenue"] - q_pnl["ncl"] - q_pnl["cof"] - q_pnl["opex"]
    q_pnl["rev_rate"] = q_pnl["revenue"] / q_pnl["anr"].replace(0,np.nan) * 4 * 100
    q_pnl["ncl_rate"] = q_pnl["ncl"]     / q_pnl["anr"].replace(0,np.nan) * 4 * 100
    q_pnl["pnl_rate"] = q_pnl["net_pnl"] / q_pnl["anr"].replace(0,np.nan) * 4 * 100
    x = np.arange(len(q_pnl))
    ax.bar(x, q_pnl["rev_rate"], label="Revenue Rate", color="#2f4b7c", alpha=0.7)
    ax.bar(x, -q_pnl["ncl_rate"], label="NCL Rate", color="#d62728", alpha=0.7)
    ax.plot(x, q_pnl["pnl_rate"], color="black", lw=2, marker="o", markersize=3, label="Net P&L Rate")
    ax.axhline(0, color="grey", lw=0.8)
    ax.yaxis.set_major_formatter(mtick.PercentFormatter())
    ax.set_xticks(x[::4]); ax.set_xticklabels(q_pnl["yyyyq"].iloc[::4], rotation=35, fontsize=8)
    ax.set_title("Quarterly Revenue, NCL & Net P&L Rate (% of ANR, ann.)")
    ax.set_ylabel("Rate (% of ANR, annualised)"); ax.legend(fontsize=9)

    # ── Year-on-Year P&L breakdown (2021–2025) ────────────────────────────────
    ax = axes[2]
    yr_pnl = panel.groupby("year").agg(
        revenue=("cnr","sum"), ncl=("ncl","sum"),
        cof=("cost_of_funds","sum"), opex=("opex","sum"),
        pnl=("pnl","sum"), anr=("ANR","sum")).reset_index()
    yr_pnl = yr_pnl.sort_values("year")

    # Annualised rates as % of ANR
    yr_pnl["rev_rate"] = yr_pnl["revenue"] / yr_pnl["anr"].replace(0,np.nan) * 12 * 100
    yr_pnl["ncl_rate"] = yr_pnl["ncl"]     / yr_pnl["anr"].replace(0,np.nan) * 12 * 100
    yr_pnl["cof_rate"] = yr_pnl["cof"]     / yr_pnl["anr"].replace(0,np.nan) * 12 * 100
    yr_pnl["opex_rate"]= yr_pnl["opex"]    / yr_pnl["anr"].replace(0,np.nan) * 12 * 100
    yr_pnl["pnl_rate"] = yr_pnl["pnl"]     / yr_pnl["anr"].replace(0,np.nan) * 12 * 100

    x = np.arange(len(yr_pnl))
    width = 0.6

    # Stacked bars: revenue up, costs down
    ax.bar(x, yr_pnl["rev_rate"],  width=width, label="Revenue Rate",    color="#2f4b7c", alpha=0.8)
    ax.bar(x, -yr_pnl["ncl_rate"], width=width, label="NCL Rate",        color="#d62728", alpha=0.8)
    ax.bar(x, -yr_pnl["cof_rate"], width=width, label="Cost of Funds",   color="#ff7f0e", alpha=0.8,
           bottom=-yr_pnl["ncl_rate"])
    ax.bar(x, -yr_pnl["opex_rate"],width=width, label="OpEx Rate",       color="#9467bd", alpha=0.8,
           bottom=-yr_pnl["ncl_rate"]-yr_pnl["cof_rate"])

    # Net P&L line
    ax.plot(x, yr_pnl["pnl_rate"], color="black", lw=2.5, marker="o",
            markersize=6, label="Net P&L Rate", zorder=5)

    # Annotate P&L rate and absolute $M on each point
    for i, row in yr_pnl.iterrows():
        ax.annotate(f"{row['pnl_rate']:.1f}%\n(${row['pnl']/1e6:.0f}M)",
                    xy=(list(x)[list(yr_pnl.index).index(i)], row["pnl_rate"]),
                    xytext=(0, 10), textcoords="offset points",
                    ha="center", fontsize=8, color="black")

    ax.axhline(0, color="grey", lw=0.8)
    ax.yaxis.set_major_formatter(mtick.PercentFormatter())
    ax.set_xticks(x)
    ax.set_xticklabels(yr_pnl["year"].astype(str), fontsize=10)
    ax.set_title("Year-on-Year P&L Components (% of ANR, ann.)\n2021–2025")
    ax.set_ylabel("Rate (% of ANR, annualised)")
    ax.legend(fontsize=8, loc="upper left")

    plt.tight_layout()
    path = f"{OUTPUT_DIR}/06_pnl_waterfall.png"
    plt.savefig(path, dpi=150, bbox_inches="tight")
    plt.close()
    print(f"  ✔ Saved {path}")
plot_pnl_waterfall(panel)

a = monthly["interest_income"].sum()
b = monthly["interchange_income"].sum()
c = monthly["late_fee"].sum()
d = monthly["ocl_fee"].sum()
rev = a + b+ c+d
print("interestIncome", a/rev)
print("interchangeIncome", b/rev)
print("LateFeesIncome", c/rev)
print("OCLFeesIncome", d/rev)

a/b

chk=panel[panel['month']=='2025-12-01']
chk['dpd_bucket_num'].value_counts()

gcl_by_quarter = (
    panel
    .groupby(["year", "quarter"])["gcl_ind"]
    .sum()
)

print(gcl_by_quarter)

print("\nTotal GCLs:", gcl_by_quarter.sum())

panel = panel.sort_values(["account_id", "year", "quarter"])

# First time an account reaches DPD 6
new_gcl = (
    panel[panel["dpd_bucket_num"] == 6]
    .groupby("account_id")
    .first()
    .groupby(["year", "quarter"])
    .size()
)

new_gcl.sum()

def plot_origination_ncl_rates(panel: pd.DataFrame):
    panel = panel.copy()

    # --- Yn: observation year relative to 2021 ---
    panel["yn"] = panel["year"] - 2021 + 1
    panel = panel[panel["yn"].between(1, 5)]

    # --- Origination month extracted from orig_date ---
    panel["vintage_month"] = pd.to_datetime(panel["orig_date"]).dt.to_period("M").astype(str)

    # ── By origination MONTH ──────────────────────────────────────────────
    orig_month = (panel.groupby(["vintage_month", "yn"])
                       .agg(ncl=("ncl", "sum"), anr=("ANR", "sum"), months=("month", "nunique"))
                       .reset_index())
    orig_month["ncl_rate"] = orig_month["ncl"] / (orig_month["anr"] / orig_month["months"]).replace(0, np.nan) * 100

    # ── By origination QUARTER ────────────────────────────────────────────
    orig_qtr = (panel.groupby(["vintage_quarter", "yn"])
                     .agg(ncl=("ncl", "sum"), anr=("ANR", "sum"), months=("month", "nunique"))
                     .reset_index())
    orig_qtr["ncl_rate"] = orig_qtr["ncl"] / (orig_qtr["anr"] / orig_qtr["months"]).replace(0, np.nan) * 100

    # ── By origination YEAR ───────────────────────────────────────────────
    orig_yr = (panel.groupby(["vintage_year", "yn"])
                    .agg(ncl=("ncl", "sum"), anr=("ANR", "sum"), months=("month", "nunique"))
                    .reset_index())
    orig_yr["ncl_rate"] = orig_yr["ncl"] / (orig_yr["anr"] / orig_yr["months"]).replace(0, np.nan) * 100

    # ── Plot ──────────────────────────────────────────────────────────────
    fig, axes = plt.subplots(3, 1, figsize=(18, 16))
    fig.suptitle("NCL Rate by Origination Cohort (Y1–Y5)", fontsize=15, fontweight="bold")

    yn_colors = {1: "steelblue", 2: "darkorange", 3: "seagreen", 4: "crimson", 5: "purple"}

    # Origination month
    ax = axes[0]
    for yn, grp in orig_month.groupby("yn"):
        grp = grp.sort_values("vintage_month")
        ax.plot(grp["vintage_month"].astype(str), grp["ncl_rate"],
                label=f"Y{yn}", color=yn_colors[yn], lw=1.8, marker="o", markersize=2)
    ax.yaxis.set_major_formatter(mtick.PercentFormatter())
    ax.set_title("By Origination Month")
    ax.set_xlabel("Origination Month")
    ax.set_ylabel("NCL Rate %")
    ax.tick_params(axis="x", rotation=45)
    ax.legend(title="Yn", fontsize=8)

    # Origination quarter
    ax = axes[1]
    for yn, grp in orig_qtr.groupby("yn"):
        grp = grp.sort_values("vintage_quarter")
        ax.plot(grp["vintage_quarter"].astype(str), grp["ncl_rate"],
                label=f"Y{yn}", color=yn_colors[yn], lw=1.8, marker="o", markersize=2)
    ax.yaxis.set_major_formatter(mtick.PercentFormatter())
    ax.set_title("By Origination Quarter")
    ax.set_xlabel("Origination Quarter")
    ax.set_ylabel("NCL Rate %")
    ax.tick_params(axis="x", rotation=45)
    ax.legend(title="Yn", fontsize=8)

    # Origination year — grouped bar
    ax = axes[2]
    orig_yr_pivot = orig_yr.pivot(index="vintage_year", columns="yn", values="ncl_rate")
    orig_yr_pivot.columns = [f"Y{c}" for c in orig_yr_pivot.columns]
    x = np.arange(len(orig_yr_pivot))
    width = 0.15
    for i, col in enumerate(orig_yr_pivot.columns):
        yn_num = int(col[1])
        ax.bar(x + i * width, orig_yr_pivot[col], width=width,
               label=col, color=yn_colors[yn_num])
    ax.yaxis.set_major_formatter(mtick.PercentFormatter())
    ax.set_title("By Origination Year")
    ax.set_xlabel("Origination Year")
    ax.set_ylabel("NCL Rate %")
    ax.set_xticks(x + width * 2)
    ax.set_xticklabels(orig_yr_pivot.index.astype(str))
    ax.legend(title="Yn", fontsize=8)

    plt.tight_layout()
    path = f"{OUTPUT_DIR}/06_origination_ncl_rates.png"
    plt.savefig(path, dpi=150, bbox_inches="tight")
    plt.close()
    print(f"  ✔ Saved {path}")

plot_origination_ncl_rates(panel)

import matplotlib.dates as mdates
def plot_roll_rate_markov(panel: pd.DataFrame, base_date=None, recovery_rate=0.30, horizon=24):
    """
    Fig 02 — Monthly DPD transition matrix (built from full history),
    cure/roll rates, and Markov chain forward loss projection
    applied to Dec 2025 live book snapshot.
    """
    import matplotlib.dates as mdates

    ORDER = ["Current","30 DPD","60 DPD","90 DPD","120 DPD","150 DPD","180+ DPD"]

    if base_date is None:
        base_date = panel["month"].max()
    base_date = pd.Timestamp(base_date)

    # ── PART A: Transition matrix from FULL historical panel ──────────────────
    # This uses every month of data — not just base_date
    # It answers: "across all history, how did accounts transition between states?"
    p = panel.sort_values(["account_id","month"]).copy()
    p["dpd_next"] = p.groupby("account_id")["dpd_bucket_label"].shift(-1)
    p = p.dropna(subset=["dpd_next"])
    p = p[p["dpd_bucket_label"].isin(ORDER) & p["dpd_next"].isin(ORDER)]

    # Raw transition counts first — useful for diagnostics
    trans_counts = (
        pd.crosstab(p["dpd_bucket_label"], p["dpd_next"])
          .reindex(index=ORDER, columns=ORDER, fill_value=0)
    )

    # Normalise row-wise to get probabilities
    matrix = trans_counts.div(trans_counts.sum(axis=1), axis=0).fillna(0)

    print("  Transition counts (full history):")
    print(trans_counts)
    print("\n  Transition matrix (probabilities):")
    print(matrix.round(3))

    # ── PART B: Starting vector from Dec 2025 snapshot ───────────────────────
    # This is SEPARATE from the matrix — just tells us where balances sit today
    live = panel[
        (panel["month"] == base_date) &
        (panel["is_charged_off"] == 0)
    ].copy()

    if live.empty:
        raise ValueError(
            f"No live accounts at {base_date.strftime('%b %Y')}. "
            f"Panel runs {panel['month'].min().strftime('%b %Y')} "
            f"to {panel['month'].max().strftime('%b %Y')}."
        )

    # Dollar balance in each DPD bucket at base_date
    state_vec = (
        live.groupby("dpd_bucket_label")["closing_balance"]
            .sum()
            .reindex(ORDER, fill_value=0)
            .values
            .astype(float)
    )

    print(f"\n  Dec 2025 live book snapshot:")
    for label, bal in zip(ORDER, state_vec):
        print(f"    {label:>12}: ${bal:>12,.0f}")
    print(f"    {'TOTAL':>12}: ${state_vec.sum():>12,.0f}")

    # ── PART C: Markov projection ─────────────────────────────────────────────
    # Apply historical transition matrix to Dec 2025 starting vector
    # month by month for `horizon` months
    P           = matrix.values          # 7×7 from full history
    current_vec = state_vec.copy()
    markov_rows = []

    for fwd in range(1, horizon + 1):
        # Each dollar in each state gets redistributed according to
        # historical transition probabilities
        next_vec = current_vec @ P

        # Bucket 6 inflow = balance that transitioned into charge-off this month
        co_inflow = next_vec[6]
        ncl_month = co_inflow * (1 - recovery_rate)

        markov_rows.append({
            "calendar_month": base_date + pd.DateOffset(months=fwd),
            "forward_month":  fwd,
            "co_inflow":      co_inflow,
            "projected_ncl":  ncl_month,
            "bal_current":    next_vec[0],
            "bal_30dpd":      next_vec[1],
            "bal_60dpd":      next_vec[2],
            "bal_90dpd":      next_vec[3],
            "bal_120dpd":     next_vec[4],
            "bal_150dpd":     next_vec[5],
            "total_live_bal": next_vec[:6].sum(),
        })

        # Charged-off balance exits the book — zero it before next iteration
        current_vec    = next_vec.copy()
        current_vec[6] = 0.0

    markov_df            = pd.DataFrame(markov_rows)
    markov_df["cum_ncl"] = markov_df["projected_ncl"].cumsum()

    # ── PLOTS ─────────────────────────────────────────────────────────────────
    fig, axes = plt.subplots(1, 3, figsize=(24, 6))
    fig.suptitle("Delinquency Roll-Rate Analysis", fontsize=15, fontweight="bold")

    # ── Panel 1: Transition heatmap ───────────────────────────────────────────
    ax = axes[0]
    sns.heatmap(
        matrix * 100, annot=True, fmt=".1f", cmap="RdYlGn_r",
        linewidths=0.4, ax=ax, vmin=0, vmax=100,
        cbar_kws={"label": "Transition %"}
    )
    ax.set_title("Monthly DPD Transition Matrix (%)\n[Built from full history]")
    ax.set_xlabel("Next Month DPD Bucket")
    ax.set_ylabel("Current Month DPD Bucket")
    ax.tick_params(axis="x", rotation=30)

    # ── Panel 2: Roll-forward vs cure rates ───────────────────────────────────
    ax = axes[1]
    roll_fwd, cure, labels = [], [], []

    for dpd in ORDER[1:]:
        idx = ORDER.index(dpd)
        row = matrix.loc[dpd] if dpd in matrix.index else pd.Series(0, index=ORDER)
        roll_fwd.append(float(row[ORDER[idx + 1]]) if idx < 6 else 0.0)
        cure.append(float(row["Current"]))
        labels.append(dpd)

    x, w = np.arange(len(labels)), 0.35
    ax.bar(x - w/2, [r * 100 for r in roll_fwd], w,
           label="Roll-Forward %",    color="#d62728", alpha=0.8)
    ax.bar(x + w/2, [c * 100 for c in cure],      w,
           label="Cure to Current %", color="#2ca02c", alpha=0.8)
    ax.set_xticks(x)
    ax.set_xticklabels(labels, rotation=20)
    ax.yaxis.set_major_formatter(mtick.PercentFormatter())
    ax.set_title("Roll-Forward vs. Cure Rates by DPD Bucket\n[From historical transition matrix]")
    ax.set_ylabel("Rate (%)")
    ax.legend()
    ax.grid(True, alpha=0.3, axis="y")

    # ── Panel 3: Markov balance migration + cumulative NCL ───────────────────
    ax = axes[2]

    bal_cols   = ["bal_current","bal_30dpd","bal_60dpd",
                  "bal_90dpd","bal_120dpd","bal_150dpd"]
    bal_labels = ["Current","30 DPD","60 DPD","90 DPD","120 DPD","150 DPD"]
    bal_colors = ["#2ca02c","#98df8a","#ffcc00","#ff7f0e","#d62728","#8c0000"]

    ax.stackplot(
        markov_df["calendar_month"],
        [markov_df[c] / 1e6 for c in bal_cols],
        labels=bal_labels,
        colors=bal_colors,
        alpha=0.85
    )

    ax2 = ax.twinx()
    ax2.plot(
        markov_df["calendar_month"],
        markov_df["cum_ncl"] / 1e6,
        color="black", lw=2, linestyle="--", label="Cumulative NCL ($M)"
    )
    ax2.set_ylabel("Cumulative NCL ($M)", fontsize=10)
    ax2.yaxis.set_major_formatter(mtick.FuncFormatter(lambda x, _: f"${x:.1f}M"))
    ax2.legend(loc="upper right", fontsize=8)

    ax.set_title(
        f"Markov Projection — Balance Migration + NCL\n"
        f"Starting vector: {base_date.strftime('%b %Y')} | "
        f"{horizon}m horizon | "
        f"{recovery_rate:.0%} recovery"
    )
    ax.set_ylabel("Live Balance ($M)")
    ax.xaxis.set_major_formatter(mdates.DateFormatter("%b %Y"))
    plt.setp(ax.xaxis.get_majorticklabels(), rotation=45, ha="right")
    ax.legend(loc="upper left", fontsize=8)
    ax.grid(True, alpha=0.3, axis="y")

    plt.tight_layout()
    path = f"{OUTPUT_DIR}/09_roll_rate_markov.png"
    plt.savefig(path, dpi=150, bbox_inches="tight")
    plt.close()

    # ── Summary ───────────────────────────────────────────────────────────────
    live_bal  = state_vec[:6].sum()
    total_ncl = markov_df["projected_ncl"].sum()
    print(f"\n  ✔ Saved {path}")
    print(f"  Transition matrix : built from {len(p):,} monthly transitions (full history)")
    print(f"  Starting vector   : {base_date.strftime('%b %Y')} | "
          f"${live_bal/1e6:.2f}M live balance | {len(live):,} accounts")
    print(f"  Projected NCL     : ${total_ncl/1e6:.2f}M over {horizon} months "
          f"({total_ncl/live_bal*100:.1f}% of opening balance)")

    return matrix, markov_df
a,b=plot_roll_rate_markov(panel, base_date="2025-12-01", horizon=24)

def behavioural_risk_segmentation(panel: pd.DataFrame, output_dir: str = OUTPUT_DIR):
    """
    Behavioural risk segmentation framework.

    Builds account-level behavioural features from panel history,
    scores and tiers each account using rule-based logic, and
    produces NCL/PnL impact summary + plots.

    Does NOT modify the original panel — all outputs are returned
    as separate dataframes.

    Returns
    -------
    behav       : account-level feature matrix with risk scores and tiers
    tier_summary: aggregated NCL/PnL metrics by behavioural risk tier
    """
    import matplotlib.dates as mdates

    TIER_ORDER  = ["Very Low Risk","Low Risk","Medium Risk","High Risk","Very High Risk"]
    TIER_COLORS = {
        "Very Low Risk":  "#2ca02c",
        "Low Risk":       "#98df8a",
        "Medium Risk":    "#ffcc00",
        "High Risk":      "#ff7f0e",
        "Very High Risk": "#d62728",
    }

    # ── PART A: Account-level behavioural feature matrix ─────────────────────
    # Aggregate from panel history — excludes post charge-off months
    print("  Building behavioural feature matrix...")

    behav = (
        panel[panel["is_charged_off"] == 0]
        .groupby("account_id")
        .agg(
            # Spend
            avg_monthly_spend     = ("monthly_spend_this_month", "mean"),
            spend_volatility      = ("monthly_spend_this_month", "std"),
            # Utilization
            avg_utilization       = ("utilization_rate",         "mean"),
            max_utilization       = ("utilization_rate",         "max"),
            # Payment
            avg_payment_ratio     = ("payment_ratio",            "mean"),
            min_payment_ratio     = ("payment_ratio",            "min"),
            # Delinquency
            max_dpd_reached       = ("dpd_bucket_num",           "max"),
            months_delinquent     = ("dpd_bucket_num",           lambda x: (x > 0).sum()),
            ever_90dpd            = ("dpd_bucket_num",           lambda x: int((x >= 3).any())),
            # Fee behaviour
            total_late_fees       = ("late_fee",                 "sum"),
            total_ocl_fees        = ("ocl_fee",                  "sum"),
            months_with_late_fee  = ("late_fee",                 lambda x: (x > 0).sum()),
            # P&L
            total_ncl             = ("ncl",                      "sum"),
            total_pnl             = ("pnl",                      "sum"),
            total_cnr             = ("cnr",                      "sum"),
            avg_anr               = ("ANR",                      "mean"),
            total_anr             = ("ANR",                      "sum"),
            # Metadata
            months_observed       = ("month",                    "count"),
            fico_score            = ("fico_score",               "first"),
            income_k              = ("income_k",                 "first"),
        )
        .reset_index()
    )

    # Derived ratios
    behav["delinquency_rate"]   = (
        behav["months_delinquent"] / behav["months_observed"]
    )
    behav["late_fee_frequency"] = (
        behav["months_with_late_fee"] / behav["months_observed"]
    )
    behav["ncl_rate_ann"]       = (
        behav["total_ncl"] /
        (behav["avg_anr"] * behav["months_observed"] / 12)
    ).fillna(0)

    # ── PART B: Rule-based risk scoring ──────────────────────────────────────
    print("  Scoring accounts...")

    def score_account(row):
        score = 0

        # Utilization (0–30 pts)
        if   row["avg_utilization"] >= 0.90: score += 30
        elif row["avg_utilization"] >= 0.75: score += 20
        elif row["avg_utilization"] >= 0.50: score += 10

        # Payment ratio (0–30 pts)
        if   row["avg_payment_ratio"] < 0.10: score += 30
        elif row["avg_payment_ratio"] < 0.20: score += 20
        elif row["avg_payment_ratio"] < 0.40: score += 10

        # Delinquency history (0–25 pts)
        if   row["max_dpd_reached"] >= 3: score += 25
        elif row["max_dpd_reached"] >= 1: score += 15

        if   row["delinquency_rate"] >= 0.20: score += 10
        elif row["delinquency_rate"] >= 0.05: score +=  5

        # Fee behaviour (0–15 pts)
        if   row["late_fee_frequency"] >= 0.20: score += 15
        elif row["late_fee_frequency"] >= 0.05: score +=  8

        return score

    behav["risk_score"] = behav.apply(score_account, axis=1)

    behav["behav_risk_tier"] = pd.Categorical(
        behav["risk_score"].map(lambda s:
            "Very High Risk" if s >= 80 else
            "High Risk"      if s >= 60 else
            "Medium Risk"    if s >= 40 else
            "Low Risk"       if s >= 20 else
            "Very Low Risk"
        ),
        categories=TIER_ORDER,
        ordered=True
    )

    print("  Tier distribution:")
    print(behav["behav_risk_tier"].value_counts().sort_index().to_string())

    # ── PART C: NCL/PnL summary by tier ──────────────────────────────────────
    # Join tier back to panel temporarily (read-only — panel not modified)
    print("  Building tier summary...")

    panel_with_tier = panel.merge(
        behav[["account_id","behav_risk_tier"]],
        on="account_id", how="left"
    )

    tier_summary = (
        panel_with_tier.groupby("behav_risk_tier", observed=True)
        .agg(
            accounts          = ("account_id",        "nunique"),
            total_anr         = ("ANR",               "sum"),
            avg_anr           = ("ANR",               "mean"),
            total_ncl         = ("ncl",               "sum"),
            total_cnr         = ("cnr",               "sum"),
            total_pnl         = ("pnl",               "sum"),
            avg_utilization   = ("utilization_rate",  "mean"),
            avg_payment_ratio = ("payment_ratio",     "mean"),
        )
        .reset_index()
    )

    tier_summary["ncl_rate_ann"]  = (
        tier_summary["total_ncl"] / tier_summary["total_anr"] * 12 * 100
    )
    tier_summary["pnl_per_acct"]  = tier_summary["total_pnl"] / tier_summary["accounts"]
    tier_summary["ncl_per_acct"]  = tier_summary["total_ncl"] / tier_summary["accounts"]
    tier_summary["cnr_margin"]    = (
        tier_summary["total_cnr"] / tier_summary["total_anr"] * 100
    )

    display(tier_summary.style
        .format({
            "total_anr":         "${:,.0f}",
            "avg_anr":           "${:,.0f}",
            "total_ncl":         "${:,.0f}",
            "total_cnr":         "${:,.0f}",
            "total_pnl":         "${:,.0f}",
            "ncl_rate_ann":      "{:.2f}%",
            "pnl_per_acct":      "${:,.0f}",
            "ncl_per_acct":      "${:,.0f}",
            "cnr_margin":        "{:.2f}%",
            "avg_utilization":   "{:.1%}",
            "avg_payment_ratio": "{:.1%}",
        })
        .background_gradient(subset=["ncl_rate_ann"], cmap="RdYlGn_r")
        .background_gradient(subset=["total_pnl"],    cmap="RdYlGn")
        .set_caption("NCL Impact and P&L by Behavioural Risk Tier")
    )

    # ── PART D: Plots ─────────────────────────────────────────────────────────
    print("  Plotting...")

    colors = [TIER_COLORS[t] for t in TIER_ORDER]
    ts     = tier_summary.set_index("behav_risk_tier").reindex(TIER_ORDER)

    fig, axes = plt.subplots(2, 3, figsize=(22, 12))
    fig.suptitle("Behavioural Risk Segmentation — NCL & P&L Impact",
                 fontsize=15, fontweight="bold")

    # Panel 1: Account count
    ax = axes[0, 0]
    ax.bar(TIER_ORDER, ts["accounts"], color=colors, alpha=0.85, edgecolor="white")
    ax.set_title("Account Count by Risk Tier")
    ax.set_ylabel("Accounts")
    ax.set_xticklabels(TIER_ORDER, rotation=20, ha="right")
    ax.grid(True, alpha=0.3, axis="y")

    # Panel 2: Annualised NCL rate
    ax = axes[0, 1]
    ax.bar(TIER_ORDER, ts["ncl_rate_ann"], color=colors, alpha=0.85, edgecolor="white")
    ax.yaxis.set_major_formatter(mtick.PercentFormatter())
    ax.set_title("Annualised NCL Rate by Risk Tier")
    ax.set_ylabel("NCL Rate % of ANR")
    ax.set_xticklabels(TIER_ORDER, rotation=20, ha="right")
    ax.grid(True, alpha=0.3, axis="y")

    # Panel 3: Total P&L
    ax = axes[0, 2]
    pnl_vals   = ts["total_pnl"] / 1e6
    bar_colors = ["#d62728" if v < 0 else c for v, c in zip(pnl_vals, colors)]
    ax.bar(TIER_ORDER, pnl_vals, color=bar_colors, alpha=0.85, edgecolor="white")
    ax.yaxis.set_major_formatter(mtick.FuncFormatter(lambda x, _: f"${x:.1f}M"))
    ax.axhline(0, color="black", lw=0.8, linestyle="--")
    ax.set_title("Total P&L by Risk Tier")
    ax.set_ylabel("P&L ($M)")
    ax.set_xticklabels(TIER_ORDER, rotation=20, ha="right")
    ax.grid(True, alpha=0.3, axis="y")

    # Panel 4: Utilization vs payment ratio scatter
    ax = axes[1, 0]
    for tier, color in TIER_COLORS.items():
        sub = behav[behav["behav_risk_tier"] == tier]
        ax.scatter(
            sub["avg_utilization"], sub["avg_payment_ratio"],
            label=tier, color=color, alpha=0.4, s=10
        )
    ax.set_title("Utilization vs Payment Ratio\n(coloured by risk tier)")
    ax.set_xlabel("Avg Utilization Rate")
    ax.set_ylabel("Avg Payment Ratio")
    ax.xaxis.set_major_formatter(mtick.PercentFormatter(1))
    ax.yaxis.set_major_formatter(mtick.PercentFormatter(1))
    ax.legend(fontsize=7, markerscale=2)
    ax.grid(True, alpha=0.3)

    # Panel 5: NCL per account
    ax = axes[1, 1]
    ax.bar(TIER_ORDER, ts["ncl_per_acct"], color=colors, alpha=0.85, edgecolor="white")
    ax.yaxis.set_major_formatter(mtick.FuncFormatter(lambda x, _: f"${x:,.0f}"))
    ax.set_title("NCL per Account by Risk Tier")
    ax.set_ylabel("NCL per Account ($)")
    ax.set_xticklabels(TIER_ORDER, rotation=20, ha="right")
    ax.grid(True, alpha=0.3, axis="y")

    # Panel 6: CNR margin
    ax = axes[1, 2]
    ax.bar(TIER_ORDER, ts["cnr_margin"], color=colors, alpha=0.85, edgecolor="white")
    ax.yaxis.set_major_formatter(mtick.PercentFormatter())
    ax.axhline(0, color="black", lw=0.8, linestyle="--")
    ax.set_title("CNR Margin % of ANR by Risk Tier")
    ax.set_ylabel("CNR Margin %")
    ax.set_xticklabels(TIER_ORDER, rotation=20, ha="right")
    ax.grid(True, alpha=0.3, axis="y")

    plt.tight_layout()
    path = f"{output_dir}/behavioural_risk_segmentation.png"
    plt.savefig(path, dpi=150, bbox_inches="tight")
    plt.close()
    print(f"  ✔ Saved {path}")

    # ── Summary print ─────────────────────────────────────────────────────────
    print(f"\n  Portfolio NCL breakdown by behavioural tier:")
    for _, row in tier_summary.iterrows():
        print(f"    {row['behav_risk_tier']:<16} | "
              f"{row['accounts']:>5,} accts | "
              f"NCL rate: {row['ncl_rate_ann']:>5.2f}% | "
              f"P&L: ${row['total_pnl']/1e6:>6.2f}M")

    return behav, tier_summary
behav, tier_summary = behavioural_risk_segmentation(panel)

def plot_scenario_sensitivity(panel: pd.DataFrame):
    """Fig 09 — P&L sensitivity to NCL rate shocks and revenue shocks."""
    fig, axes = plt.subplots(1, 2, figsize=(16, 7))
    fig.suptitle("P&L Scenario Sensitivity Analysis", fontsize=15, fontweight="bold")

    # Base metrics (annualised, $M)
    base_anr     = panel["ANR"].sum() / 5        # 5-year portfolio
    base_rev     = panel["cnr"].sum() / 5
    base_ncl     = panel["ncl"].sum() / 5
    base_cof     = panel["cost_of_funds"].sum() / 5
    base_opex    = panel["opex"].sum() / 5
    base_pnl     = base_rev - base_ncl - base_cof - base_opex

    ncl_rate_base = base_ncl / base_anr

    # ── A: NCL stress tornado ─────────────────────────────────────────────────
    ax = axes[0]
    shocks   = [-0.020, -0.010, 0.000, +0.010, +0.020, +0.030, +0.050]  # absolute pp on NCL rate
    pnl_vals = [(base_rev - (ncl_rate_base + s)*base_anr - base_cof - base_opex)/1e6
                for s in shocks]
    shock_labels = [f"{'+' if s>=0 else ''}{s*100:.0f}pp" for s in shocks]
    bar_colors   = ["#2ca02c" if v>=base_pnl/1e6 else "#d62728" for v in pnl_vals]
    ax.barh(shock_labels, pnl_vals, color=bar_colors, alpha=0.85, edgecolor="white")
    ax.axvline(base_pnl/1e6, color="black", lw=1.5, ls="--", label=f"Base P&L ${base_pnl/1e6:.0f}M")
    ax.xaxis.set_major_formatter(mtick.FuncFormatter(lambda x,_:f"${x:.0f}M"))
    ax.set_title("Net P&L Sensitivity to NCL Rate Shocks (±pp)\n(Annual, $M)")
    ax.set_xlabel("Net P&L ($M, ann.)"); ax.legend(fontsize=9)
    for i, v in enumerate(pnl_vals):
        ax.text(v + (base_pnl/1e6)*0.01, i, f"${v:.0f}M", va="center", fontsize=8)

    # ── B: 2-way sensitivity table (NCL shock × revenue shock) ────────────────
    ax = axes[1]
    ncl_shocks = [-0.010, 0.0, +0.010, +0.020, +0.030]
    rev_shocks = [-0.05, -0.02, 0.0, +0.02, +0.05]
    table_data = np.zeros((len(ncl_shocks), len(rev_shocks)))
    for i, ns in enumerate(ncl_shocks):
        for j, rs in enumerate(rev_shocks):
            pnl_s = (base_rev*(1+rs) - (ncl_rate_base+ns)*base_anr - base_cof - base_opex)/1e6
            table_data[i,j] = pnl_s

    sns.heatmap(table_data,
                xticklabels=[f"{'+' if r>=0 else ''}{r*100:.0f}%" for r in rev_shocks],
                yticklabels=[f"{'+' if n>=0 else ''}{n*100:.0f}pp" for n in ncl_shocks],
                annot=True, fmt=".0f", cmap="RdYlGn", center=base_pnl/1e6,
                ax=ax, cbar_kws={"label":"Net P&L $M (ann.)"}, linewidths=0.3)
    ax.set_xlabel("Revenue Rate Shock"); ax.set_ylabel("NCL Rate Shock")
    ax.set_title("2-Way P&L Sensitivity: NCL Shock × Revenue Shock\n($M ann. — green = above base)")

    plt.tight_layout()
    path = f"{OUTPUT_DIR}/09_scenario_sensitivity.png"
    plt.savefig(path, dpi=150, bbox_inches="tight")
    plt.close()
    print(f"  ✔ Saved {path}")

plot_scenario_sensitivity(panel)

def plot_bureau_distributions(df: pd.DataFrame):
    """Fig 01 — FICO / Vantage score distributions by tier and card type."""
    fig, axes = plt.subplots(2, 2, figsize=(14, 9))
    fig.suptitle("Portfolio Bureau Score Distributions", fontsize=15, fontweight="bold", y=1.01)

    tier_order  = ["Deep Subprime","Subprime","Near Prime","Prime","Super Prime"]
    tier_colors = [RISK_COLORS[t] for t in tier_order]

    # Panel A: FICO distribution overall (KDE + histogram)
    ax = axes[0,0]
    ax.hist(df["fico_score"], bins=50, color="#2f4b7c", alpha=0.6, density=True, label="Histogram")
    kde_x = np.linspace(300,850,300)
    kde   = stats.gaussian_kde(df["fico_score"])
    ax.plot(kde_x, kde(kde_x), color="#d62728", lw=2, label="KDE")
    ax.axvline(df["fico_score"].median(), ls="--", color="black", lw=1.2, label=f'Median {df["fico_score"].median():.0f}')
    ax.set_title("FICO Score — Full Portfolio")
    ax.set_xlabel("FICO Score"); ax.set_ylabel("Density")
    ax.legend(fontsize=9)

    # Panel B: FICO by tier (stacked histogram)
    ax = axes[0,1]
    for tier, color in zip(tier_order, tier_colors):
        sub = df[df["fico_tier"]==tier]["fico_score"]
        ax.hist(sub, bins=40, alpha=0.65, label=tier, color=color, density=False)
    ax.set_title("FICO Score by Risk Tier")
    ax.set_xlabel("FICO Score"); ax.set_ylabel("Account Count")
    ax.legend(fontsize=8)

    # Panel C: FICO by card type
    ax = axes[1,0]
    for ct, color in CARD_COLORS.items():
        sub = df[df["card_type"]==ct]["fico_score"]
        ax.hist(sub, bins=40, alpha=0.7, label=ct, color=color, density=True)
    ax.set_title("FICO Score by Card Type")
    ax.set_xlabel("FICO Score"); ax.set_ylabel("Density")
    ax.legend()

    # Panel D: Risk tier mix (donut)
    ax = axes[1,1]
    tier_counts = df["fico_tier"].value_counts().reindex(tier_order).dropna()
    wedges, texts, autotexts = ax.pie(
        tier_counts, labels=tier_counts.index,
        colors=tier_colors[:len(tier_counts)], autopct="%1.1f%%",
        startangle=90, pctdistance=0.8,
        wedgeprops=dict(width=0.5))
    for t in autotexts: t.set_fontsize(8)
    ax.set_title("Portfolio Risk Tier Mix")

    plt.tight_layout()
    path = f"{OUTPUT_DIR}/01_fico_distribution.png"
    plt.savefig(path, dpi=150, bbox_inches="tight")
    plt.close()
    print(f"  ✔ Saved {path}")

plot_bureau_distributions(panel)

def plot_delinquency_trend(panel: pd.DataFrame):
    """Fig 04 — Monthly DPD distribution stacked area chart."""
    order  = ["Current","30 DPD","60 DPD","90 DPD","120 DPD","150 DPD","180+ DPD"]
    colors = ["#2ca02c","#bcbd22","#ff7f0e","#d62728","#9467bd","#8c564b","#7f7f7f"]

    monthly_dpd = (panel.groupby(["month","dpd_bucket_label"])
                        .size().unstack(fill_value=0))
    monthly_dpd = monthly_dpd.reindex(columns=order, fill_value=0)
    monthly_dpd_pct = monthly_dpd.div(monthly_dpd.sum(axis=1), axis=0) * 100

    fig, axes = plt.subplots(2, 1, figsize=(14, 10))
    fig.suptitle("Portfolio Delinquency Trend Analysis", fontsize=15, fontweight="bold")

    ax = axes[0]
    ax.stackplot(monthly_dpd_pct.index, [monthly_dpd_pct[c] for c in order],
                 labels=order, colors=colors, alpha=0.85)
    ax.yaxis.set_major_formatter(mtick.PercentFormatter())
    ax.set_title("Monthly DPD Distribution (% of Portfolio)")
    ax.set_ylabel("Share of Portfolio (%)"); ax.set_xlim(monthly_dpd_pct.index[0],monthly_dpd_pct.index[-1])
    ax.legend(loc="upper left", fontsize=8, ncol=4)

    # Monthly charge-off rate (annualized)
    ax = axes[1]
    monthly_co = panel.groupby("month").agg(ncl=("ncl","sum"), anr=("ANR","sum"))
    monthly_co["ncl_rate_ann"] = monthly_co["ncl"] / monthly_co["anr"].replace(0,np.nan) * 12 * 100
    ax.plot(monthly_co.index, monthly_co["ncl_rate_ann"], color="#d62728", lw=2, label="NCL Rate (ann.)")
    ax.fill_between(monthly_co.index, monthly_co["ncl_rate_ann"], alpha=0.15, color="#d62728")
    ax.yaxis.set_major_formatter(mtick.PercentFormatter())
    ax.set_title("Annualised Net Credit Loss Rate (monthly)")
    ax.set_ylabel("NCL Rate (% of ANR, ann.)"); ax.legend()

    plt.tight_layout()
    path = f"{OUTPUT_DIR}/04_delinquency_trend.png"
    plt.savefig(path, dpi=150, bbox_inches="tight")
    plt.close()
    print(f"  ✔ Saved {path}")
plot_delinquency_trend(panel)

def plot_risk_segmentation(panel: pd.DataFrame):
    """Fig 05 — P&L and NCL breakdown by FICO tier, card type, and segment."""
    fig = plt.figure(figsize=(16, 12))
    gs  = GridSpec(2, 3, figure=fig, hspace=0.4, wspace=0.35)
    fig.suptitle("Risk Segmentation — NCL & P&L Decomposition", fontsize=15, fontweight="bold")

    tier_order = ["Deep Subprime","Subprime","Near Prime","Prime","Super Prime"]
    tier_colors= [RISK_COLORS[t] for t in tier_order]

    # --- A: NCL rate by FICO tier ---
    ax = fig.add_subplot(gs[0,0])
    seg_agg = panel.groupby("fico_tier").agg(ncl=("ncl","sum"), anr=("ANR","sum")).reindex(tier_order)
    ncl_rate = (seg_agg["ncl"] / seg_agg["anr"].replace(0,np.nan) * 12 * 100).fillna(0)
    bars = ax.bar(tier_order, ncl_rate, color=tier_colors, alpha=0.85, edgecolor="white")
    for bar, v in zip(bars, ncl_rate):
        ax.text(bar.get_x()+bar.get_width()/2, bar.get_height()+0.05, f"{v:.1f}%",
                ha="center", va="bottom", fontsize=8)
    ax.set_title("Ann. NCL Rate by FICO Tier"); ax.set_ylabel("NCL Rate (%)")
    ax.yaxis.set_major_formatter(mtick.PercentFormatter())
    ax.set_xticklabels(tier_order, rotation=20, ha="right", fontsize=8)

    # --- B: Net P&L per $1,000 ANR by FICO tier ---
    ax = fig.add_subplot(gs[0,1])
    pnl_agg = panel.groupby("fico_tier").agg(
        pnl=("pnl","sum"), anr=("ANR","sum")).reindex(tier_order)
    pnl_per_k = (pnl_agg["pnl"] / pnl_agg["anr"].replace(0,np.nan) * 1000).fillna(0)
    colors_ = ["#2ca02c" if v>=0 else "#d62728" for v in pnl_per_k]
    bars = ax.bar(tier_order, pnl_per_k, color=colors_, alpha=0.85, edgecolor="white")
    ax.axhline(0, color="black", lw=0.8)
    for bar, v in zip(bars, pnl_per_k):
        ax.text(bar.get_x()+bar.get_width()/2,
                bar.get_height()+(0.5 if v>=0 else -1.5), f"${v:.1f}",
                ha="center", va="bottom", fontsize=8)
    ax.set_title("Net P&L per $1,000 ANR by FICO Tier"); ax.set_ylabel("$/1,000 ANR")
    ax.set_xticklabels(tier_order, rotation=20, ha="right", fontsize=8)

    # --- C: ANR concentration by FICO tier ---
    ax = fig.add_subplot(gs[0,2])
    anr_mix = seg_agg["anr"] / seg_agg["anr"].sum() * 100
    ax.barh(tier_order, anr_mix, color=tier_colors, alpha=0.85, edgecolor="white")
    ax.xaxis.set_major_formatter(mtick.PercentFormatter())
    ax.set_title("ANR Concentration by FICO Tier"); ax.set_xlabel("% of Total ANR")

    # --- D: NCL rate by card type ---
    ax = fig.add_subplot(gs[1,0])
    ct_agg = panel.groupby("card_type").agg(ncl=("ncl","sum"), anr=("ANR","sum"))
    ct_ncl = (ct_agg["ncl"]/ct_agg["anr"].replace(0,np.nan)*12*100).fillna(0)
    ct_colors = [CARD_COLORS.get(c,"grey") for c in ct_ncl.index]
    ax.bar(ct_ncl.index, ct_ncl, color=ct_colors, alpha=0.85, edgecolor="white")
    ax.yaxis.set_major_formatter(mtick.PercentFormatter())
    ax.set_title("Ann. NCL Rate by Card Type"); ax.set_ylabel("NCL Rate (%)")

    # --- E: Revenue waterfall components by FICO tier ---
    ax = fig.add_subplot(gs[1,1])
    rev_comp = panel.groupby("fico_tier").agg(
        interest=("interest_income","sum"), interchange=("interchange_income","sum"),
        fees=("late_fee","sum"), anr=("ANR","sum")).reindex(tier_order)
    rev_comp_k = rev_comp[["interest","interchange","fees"]].div(rev_comp["anr"], axis=0)*12*100
    rev_comp_k.plot(kind="bar", ax=ax, color=["#003f5c","#a05195","#ffa600"], alpha=0.85, width=0.7)
    ax.yaxis.set_major_formatter(mtick.PercentFormatter())
    ax.set_title("Revenue Components by FICO Tier (% ANR ann.)"); ax.set_ylabel("Rate (%)")
    ax.set_xticklabels(tier_order, rotation=20, ha="right", fontsize=8)
    ax.legend(["Interest","Interchange","Fees"], fontsize=8)

    # # --- F: Utilization vs NCL rate scatter (by segment) ---
    # ax = fig.add_subplot(gs[1,2])
    # seg_scatter = panel.groupby("segment").agg(
    #     ncl_rate=("ncl","sum"), anr=("ANR","sum"), util=("utilization_rate","mean")).reset_index()
    # seg_scatter["ncl_ann"] = seg_scatter["ncl_rate"]/seg_scatter["anr"].replace(0,np.nan)*12*100
    # sizes = (seg_scatter["anr"] / seg_scatter["anr"].max() * 400).fillna(50)
    # sc = ax.scatter(seg_scatter["util"]*100, seg_scatter["ncl_ann"], s=sizes,
    #                 c=range(len(seg_scatter)), cmap="viridis", alpha=0.8, edgecolors="white")
    # for _, row in seg_scatter.iterrows():
    #     ax.annotate(row["segment"].replace("_","\n"), (row["util"]*100, row["ncl_ann"]),
    #                 fontsize=7, ha="center")
    # ax.xaxis.set_major_formatter(mtick.PercentFormatter())
    # ax.yaxis.set_major_formatter(mtick.PercentFormatter())
    # ax.set_title("Utilization vs NCL Rate by Segment\n(bubble = ANR share)")
    # ax.set_xlabel("Avg Utilization Rate"); ax.set_ylabel("Ann. NCL Rate (%)")

    path = f"{OUTPUT_DIR}/05_risk_segmentation.png"
    plt.savefig(path, dpi=150, bbox_inches="tight")
    plt.close()
    print(f"  ✔ Saved {path}")
plot_risk_segmentation(panel)

panel.columns

def plot_pnl_by_vintage(panel: pd.DataFrame):
    """Fig 07 — P&L breakdown by origination month / quarter."""
    fig, axes = plt.subplots(2, 2, figsize=(16, 12))
    fig.suptitle("P&L Analysis by Origination Vintage", fontsize=15, fontweight="bold")

    # ── A: Cumulative P&L by vintage year ────────────────────────────────────
    ax = axes[0,0]
    vy_pnl = panel.groupby(["vintage_year","months_on_book"]).agg(
        pnl=("pnl","sum"), anr=("ANR","sum")).reset_index()
    vy_pnl = vy_pnl.sort_values(["vintage_year","months_on_book"])
    years = sorted(vy_pnl["vintage_year"].unique())
    cmap  = plt.cm.tab10(np.linspace(0,0.9,len(years)))
    for yr, color in zip(years, cmap):
        sub = vy_pnl[vy_pnl["vintage_year"]==yr]
        cum = sub["pnl"].cumsum() / 1e6
        ax.plot(sub["months_on_book"], cum, label=str(yr), color=color, lw=2)
    ax.axhline(0, color="grey", lw=0.8, ls="--")
    ax.set_title("Cumulative P&L by Vintage Year")
    ax.set_xlabel("Months on Book"); ax.set_ylabel("Cumulative P&L ($M)")
    ax.yaxis.set_major_formatter(mtick.FuncFormatter(lambda x,_:f"${x:.0f}M"))
    ax.legend(title="Vintage Year", fontsize=8)

    # ── B: P&L heatmap (vintage quarter × observation year) ──────────────────
    ax = axes[0,1]
    vq_yr = panel.groupby(["vintage_quarter","year"]).agg(
        pnl=("pnl","sum"), anr=("ANR","sum")).reset_index()
    vq_yr["pnl_rate"] = vq_yr["pnl"] / vq_yr["anr"].replace(0,np.nan) * 12 * 100
    pivot = vq_yr.pivot(index="vintage_quarter", columns="year", values="pnl_rate")
    sns.heatmap(pivot, annot=True, fmt=".1f", cmap="RdYlGn",
                center=0, linewidths=0.3, ax=ax, cbar_kws={"label":"Net P&L Rate % ann."})
    ax.set_title("Net P&L Rate (%) — Vintage Quarter × Observation Year")
    ax.set_xlabel("Observation Year"); ax.set_ylabel("Origination Quarter")
    ax.tick_params(axis="y", labelsize=6)

    # ── C: Revenue, NCL, CoF, P&L breakdown by origination quarter ───────────
    ax = axes[1,0]
    vq_summary = panel.groupby("vintage_quarter").agg(
        rev=("cnr","sum"), ncl=("ncl","sum"),
        cof=("cost_of_funds","sum"), pnl=("pnl","sum"),
        anr=("ANR","sum")).reset_index()
    vq_summary["rev_r"] = vq_summary["rev"] / vq_summary["anr"].replace(0,np.nan) * 12 * 100
    vq_summary["ncl_r"] = vq_summary["ncl"] / vq_summary["anr"].replace(0,np.nan) * 12 * 100
    vq_summary["cof_r"] = vq_summary["cof"] / vq_summary["anr"].replace(0,np.nan) * 12 * 100
    vq_summary["pnl_r"] = vq_summary["pnl"] / vq_summary["anr"].replace(0,np.nan) * 12 * 100
    x = np.arange(len(vq_summary))
    ax.bar(x, vq_summary["rev_r"], label="Revenue Rate", color="#2f4b7c", alpha=0.75)
    ax.bar(x, -vq_summary["ncl_r"], label="NCL Rate", color="#d62728", alpha=0.75)
    ax.bar(x, -vq_summary["cof_r"], bottom=-vq_summary["ncl_r"],
           label="Cost of Funds", color="#ff7f0e", alpha=0.75)
    ax.plot(x, vq_summary["pnl_r"], color="black", lw=2, marker="o",
            markersize=3, label="Net P&L Rate")
    ax.axhline(0, color="grey", lw=0.8)
    ax.yaxis.set_major_formatter(mtick.PercentFormatter())
    ax.set_xticks(x[::4]); ax.set_xticklabels(vq_summary["vintage_quarter"].iloc[::4],
                                                rotation=35, fontsize=8)
    ax.set_title("P&L Components by Origination Quarter (% ANR ann.)")
    ax.set_ylabel("Rate (% ANR ann.)"); ax.legend(fontsize=8)

    # ── D: Break-even MOB by vintage year ────────────────────────────────────
    ax = axes[1,1]
    be_mob = {}
    for yr in years:
        sub = vy_pnl[vy_pnl["vintage_year"]==yr].sort_values("months_on_book")
        cum_pnl = sub["pnl"].cumsum()
        be_idx  = cum_pnl[cum_pnl>=0].index
        be_mob[yr] = sub.loc[be_idx[0],"months_on_book"] if len(be_idx)>0 else np.nan
    be_df = pd.DataFrame(list(be_mob.items()), columns=["vintage_year","break_even_mob"])
    bars  = ax.bar(be_df["vintage_year"].astype(str), be_df["break_even_mob"],
                   color=[plt.cm.tab10(i/10) for i in range(len(be_df))], alpha=0.85)
    for bar, v in zip(bars, be_df["break_even_mob"]):
        if not np.isnan(v):
            ax.text(bar.get_x()+bar.get_width()/2, v+0.3, f"{v:.0f}m",
                    ha="center", va="bottom", fontsize=9)
    ax.set_title("Break-Even MOB by Vintage Year\n(month cumulative P&L turns positive)")
    ax.set_xlabel("Vintage Year"); ax.set_ylabel("Months on Book to Break-Even")

    plt.tight_layout()
    path = f"{OUTPUT_DIR}/07_pnl_by_vintage.png"
    plt.savefig(path, dpi=150, bbox_inches="tight")
    plt.close()
    print(f"  ✔ Saved {path}")
plot_pnl_by_vintage(panel)

def plot_scenario_sensitivity(panel: pd.DataFrame):
    """Fig 09 — P&L sensitivity to NCL rate shocks and revenue shocks."""
    fig, axes = plt.subplots(1, 2, figsize=(16, 7))
    fig.suptitle("P&L Scenario Sensitivity Analysis", fontsize=15, fontweight="bold")

    # Base metrics (annualised, $M)
    base_anr     = panel["ANR"].sum() / 5        # 5-year portfolio
    base_rev     = panel["cnr"].sum() / 5
    base_ncl     = panel["ncl"].sum() / 5
    base_cof     = panel["cost_of_funds"].sum() / 5
    base_opex    = panel["opex"].sum() / 5
    base_pnl     = base_rev - base_ncl - base_cof - base_opex

    ncl_rate_base = base_ncl / base_anr

    # ── A: NCL stress tornado ─────────────────────────────────────────────────
    ax = axes[0]
    shocks   = [-0.020, -0.010, 0.000, +0.010, +0.020, +0.030, +0.050]  # absolute pp on NCL rate
    pnl_vals = [(base_rev - (ncl_rate_base + s)*base_anr - base_cof - base_opex)/1e6
                for s in shocks]
    shock_labels = [f"{'+' if s>=0 else ''}{s*100:.0f}pp" for s in shocks]
    bar_colors   = ["#2ca02c" if v>=base_pnl/1e6 else "#d62728" for v in pnl_vals]
    ax.barh(shock_labels, pnl_vals, color=bar_colors, alpha=0.85, edgecolor="white")
    ax.axvline(base_pnl/1e6, color="black", lw=1.5, ls="--", label=f"Base P&L ${base_pnl/1e6:.0f}M")
    ax.xaxis.set_major_formatter(mtick.FuncFormatter(lambda x,_:f"${x:.0f}M"))
    ax.set_title("Net P&L Sensitivity to NCL Rate Shocks (±pp)\n(Annual, $M)")
    ax.set_xlabel("Net P&L ($M, ann.)"); ax.legend(fontsize=9)
    for i, v in enumerate(pnl_vals):
        ax.text(v + (base_pnl/1e6)*0.01, i, f"${v:.0f}M", va="center", fontsize=8)

    # ── B: 2-way sensitivity table (NCL shock × revenue shock) ────────────────
    ax = axes[1]
    ncl_shocks = [-0.010, 0.0, +0.010, +0.020, +0.030]
    rev_shocks = [-0.05, -0.02, 0.0, +0.02, +0.05]
    table_data = np.zeros((len(ncl_shocks), len(rev_shocks)))
    for i, ns in enumerate(ncl_shocks):
        for j, rs in enumerate(rev_shocks):
            pnl_s = (base_rev*(1+rs) - (ncl_rate_base+ns)*base_anr - base_cof - base_opex)/1e6
            table_data[i,j] = pnl_s

    sns.heatmap(table_data,
                xticklabels=[f"{'+' if r>=0 else ''}{r*100:.0f}%" for r in rev_shocks],
                yticklabels=[f"{'+' if n>=0 else ''}{n*100:.0f}pp" for n in ncl_shocks],
                annot=True, fmt=".0f", cmap="RdYlGn", center=base_pnl/1e6,
                ax=ax, cbar_kws={"label":"Net P&L $M (ann.)"}, linewidths=0.3)
    ax.set_xlabel("Revenue Rate Shock"); ax.set_ylabel("NCL Rate Shock")
    ax.set_title("2-Way P&L Sensitivity: NCL Shock × Revenue Shock\n($M ann. — green = above base)")

    plt.tight_layout()
    path = f"{OUTPUT_DIR}/09_scenario_sensitivity.png"
    plt.savefig(path, dpi=150, bbox_inches="tight")
    plt.close()
    print(f"  ✔ Saved {path}")

def plot_scenario_sensitivity(panel: pd.DataFrame):
    """Fig 09 — P&L sensitivity to NCL rate shocks and revenue shocks."""
    fig, axes = plt.subplots(1, 3, figsize=(24, 7))
    fig.suptitle("P&L Scenario Sensitivity Analysis", fontsize=15, fontweight="bold")

    # Base metrics (annualised, $M)
    base_anr     = panel["ANR"].sum() / 5
    base_rev     = panel["cnr"].sum() / 5
    base_ncl     = panel["ncl"].sum() / 5
    base_cof     = panel["cost_of_funds"].sum() / 5
    base_opex    = panel["opex"].sum() / 5
    base_pnl     = base_rev - base_ncl - base_cof - base_opex
    ncl_rate_base = base_ncl / base_anr

    def compute_pnl(ncl_shock=0.0, rev_shock=0.0):
        return (base_rev * (1 + rev_shock)
                - (ncl_rate_base + ncl_shock) * base_anr
                - base_cof - base_opex) / 1e6

    # ── A: NCL stress tornado ─────────────────────────────────────────────────
    ax = axes[0]
    shocks      = [-0.020, -0.010, 0.000, +0.010, +0.020, +0.030, +0.050]
    pnl_vals    = [compute_pnl(ncl_shock=s) for s in shocks]
    shock_labels= [f"{'+' if s>=0 else ''}{s*100:.0f}pp" for s in shocks]
    bar_colors  = ["#2ca02c" if v >= base_pnl/1e6 else "#d62728" for v in pnl_vals]
    ax.barh(shock_labels, pnl_vals, color=bar_colors, alpha=0.85, edgecolor="white")
    ax.axvline(base_pnl/1e6, color="black", lw=1.5, ls="--",
               label=f"Base P&L ${base_pnl/1e6:.0f}M")
    ax.xaxis.set_major_formatter(mtick.FuncFormatter(lambda x, _: f"${x:.0f}M"))
    ax.set_title("Net P&L Sensitivity to NCL Rate Shocks (±pp)\n(Annual, $M)")
    ax.set_xlabel("Net P&L ($M, ann.)")
    ax.legend(fontsize=9)
    for i, v in enumerate(pnl_vals):
        ax.text(v + (base_pnl/1e6)*0.01, i, f"${v:.0f}M", va="center", fontsize=8)

    # ── B: 2-way sensitivity heatmap ──────────────────────────────────────────
    ax = axes[1]
    ncl_shocks = [-0.010, 0.0, +0.010, +0.020, +0.030]
    rev_shocks = [-0.05, -0.02, 0.0, +0.02, +0.05]
    table_data = np.array([[compute_pnl(ns, rs) for rs in rev_shocks]
                            for ns in ncl_shocks])
    sns.heatmap(table_data,
                xticklabels=[f"{'+' if r>=0 else ''}{r*100:.0f}%" for r in rev_shocks],
                yticklabels=[f"{'+' if n>=0 else ''}{n*100:.0f}pp" for n in ncl_shocks],
                annot=True, fmt=".0f", cmap="RdYlGn", center=base_pnl/1e6,
                ax=ax, cbar_kws={"label": "Net P&L $M (ann.)"}, linewidths=0.3)
    ax.set_xlabel("Revenue Rate Shock")
    ax.set_ylabel("NCL Rate Shock")
    ax.set_title("2-Way P&L Sensitivity: NCL Shock × Revenue Shock\n($M ann. — green = above base)")

    # ── C: Probability-weighted scenario analysis ─────────────────────────────
    ax = axes[2]
    scenarios = {
        "Base":          {"ncl_shock": 0.000, "rev_shock":  0.000, "prob": 0.50},
        "Mild Downside": {"ncl_shock": 0.010, "rev_shock": -0.020, "prob": 0.25},
        "Severe":        {"ncl_shock": 0.030, "rev_shock": -0.050, "prob": 0.15},
        "Stress":        {"ncl_shock": 0.050, "rev_shock": -0.100, "prob": 0.10},
    }

    scenario_pnls    = {name: compute_pnl(s["ncl_shock"], s["rev_shock"])
                        for name, s in scenarios.items()}
    expected_pnl     = sum(scenarios[n]["prob"] * scenario_pnls[n] for n in scenarios)
    scenario_colors  = ["#2ca02c" if v >= 0 else "#d62728"
                        for v in scenario_pnls.values()]

    bars = ax.bar(scenario_pnls.keys(), scenario_pnls.values(),
                  color=scenario_colors, alpha=0.85, edgecolor="white", width=0.5)

    # Annotate each bar with P&L, probability, and contribution to EV
    for bar, (name, pnl) in zip(bars, scenario_pnls.items()):
        prob = scenarios[name]["prob"]
        ax.text(bar.get_x() + bar.get_width()/2,
                bar.get_height() + abs(bar.get_height())*0.02,
                f"${pnl:.0f}M\np={prob:.0%}",
                ha="center", va="bottom", fontsize=8)

    # Expected P&L line
    ax.axhline(expected_pnl, color="navy", lw=1.5, ls="--",
               label=f"Expected P&L ${expected_pnl:.0f}M")
    ax.axhline(0, color="black", lw=0.8, ls=":")
    ax.yaxis.set_major_formatter(mtick.FuncFormatter(lambda x, _: f"${x:.0f}M"))
    ax.set_title("Probability-Weighted Scenario P&L\n(ann. $M)")
    ax.set_ylabel("Net P&L ($M, ann.)")
    ax.legend(fontsize=9)

    plt.tight_layout()
    path = f"{OUTPUT_DIR}/09_scenario_sensitivity.png"
    plt.savefig(path, dpi=150, bbox_inches="tight")
    plt.close()
    print(f"  ✔ Saved {path}")

plot_scenario_sensitivity(panel)

